services:
  app:
    image: node:22
    container_name: user_mgmt_app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/user_management
    volumes:
      - ./:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: user_mgmt_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: user_management
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: user_mgmt_mongo_express
    restart: unless-stopped
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

volumes:
  mongo_data:
